// Ronnie Scott's seed — captured via a real browser 2026-07-16 (their WAF
// 403s every non-browser client, residential IPs included). Format:
// [slug, title, date, room] with room M=Main, U=Upstairs, L=Late Late,
// X=Late Late Upstairs. REFRESH by asking Claude to re-capture; retire
// if their WAF ever relents (crawl() tries live first).
export const SEED = [["sharlene-hector","Sharlene Hector","2026-07-16","U"],
  ["eliane-elias","Eliane Elias","2026-07-16","M"],
  ["ed-hogben","Late Late Show Upstairs with Ed Hogben","2026-07-16","X"],
  ["late-late-show-with-alex-hitchcock","Late Late Show with Alex Hitchcock","2026-07-16","L"],
  ["vula-2","Vula","2026-07-17","U"],
  ["kenny-garrett-and-sounds-from-the-ancestors","Kenny Garrett and Sounds From The Ancestors","2026-07-19","M"],
  ["asa-martinson-the-outlet","Asa Martinson & The Outlet","2026-07-17","U"],
  ["late-late-electronic-with-nana-rizinni","Late Late Electronic with Naná Rizinni","2026-07-17","L"],
  ["donovan-haffner","Donovan Haffner","2026-07-18","U"],
  ["tenderlonious-upstairs-at-ronnies","Late Late Show Upstairs with N22","2026-10-17","X"],
  ["late-late-show-with-kyra","Late Late Show with Kyra","2026-07-18","L"],
  ["kenny-garrett-and-sounds-from-the-ancestors-2","Kenny Garrett and Sounds From The Ancestors","2026-07-19","M"],
  ["cellophonics","Cellophonics: Wood on the Tracks","2026-07-20","U"],
  ["say-she-she","Say She She","2026-07-20","M"],
  ["ronnie-scotts-jazz-jam-1","Ronnie Scott's Jazz Jam","2026-11-09","L"],
  ["peter-somuah-group","Peter Somuah Group","2026-07-21","U"],
  ["isaiah-collier-the-chosen-few","Isaiah Collier","2026-07-21","M"],
  ["emma-smith-jamie-safir-trio","Emma Smith & Jamie Safir Trio","2026-08-26","U"],
  ["mica-paris","Mica Paris","2026-07-29","M"],
  ["nikki-yeoh-jay-verma","Late Late Show with Nikki Yeoh's Nucleus Sessions and Jay Verma","2026-07-22","L"],
  ["heidi-vogel","Heidi Vogel","2026-07-23","U"],
  ["binker-golding","Binker Golding","2026-07-23","M"],
  ["michelle-john","Michelle John","2026-07-24","U"],
  ["carmen-lundy","Carmen Lundy","2026-07-25","M"],
  ["late-late-electronic-chiminyo","Late Late Electronic hosted by Chiminyo","2026-12-11","L"],
  ["zoe-kypri","Zoe Kypri","2026-07-25","U"],
  ["late-late-show-upstairs-with-energy-exchange-records","Late Late Show Upstairs with Energy Exchange Records","2026-11-28","X"],
  ["late-late-show-hosted-by-hoos-collective","Late Late Show hosted by Hoos Collective","2026-07-25","L"],
  ["nina-kristofferson-sings-billie-holiday","Nina Kristofferson sings Billie Holiday","2026-07-26","M"],
  ["ronnie-scotts-all-stars-a-night-at-the-movies","Ronnie Scott’s All Stars: A Night at The Movies","2026-07-26","U"],
  ["w3-funk-sessions-3","W3 Funk Sessions","2026-12-27","M"],
  ["imogen-whitehead-and-patrick-milne","Imogen Whitehead and Patrick Milne","2026-07-27","U"],
  ["solomon-gundy-band","The Solomon Gundy Band","2026-07-27","M"],
  ["finn-carter","Piano Trio Series: Finn Carter","2026-07-28","U"],
  ["ivan-lins","Ivan Lins","2026-07-30","M"],
  ["late-late-show-with-jd3","Late Late Show Upstairs with JD3","2026-11-07","X"],
  ["late-late-show-hosted-by-myele-manzanza","Late Late Show hosted by Myele Manzanza","2026-07-30","L"],
  ["jo-harrop-2","Jo Harrop","2026-07-31","U"],
  ["jeremy-ledbetter","Jeremy Ledbetter Trio","2026-07-31","M"],
  ["late-late-show-hosted-by-the-future-movers","Late Late Show with Future Movers","2026-12-05","L"],
  ["ronnie-scotts-street-party-2026","Ronnie Scott's Street Party 2026","2026-08-01","M"],
  ["marlon-the-pannist-2","Marlon The Pannist","2026-08-01","U"],
  ["kenny-barron","Kenny Barron: Songbook","2026-08-01","M"],
  ["neone-the-wonderer-2","NEONE The Wonderer","2026-08-01","U"],
  ["olivia-cuttill-quintet","Olivia Cuttill Quintet","2026-08-02","M"],
  ["ronnie-scotts-gospel-choir","Ronnie Scott's Gospel Choir led by Daniel Thomas","2026-11-01","U"],
  ["ronnie-scotts-blues-explosion-5","Ronnie Scott's Blues Explosion","2026-11-01","M"],
  ["the-blackbyrds","The Blackbyrds","2026-08-04","M"],
  ["bruno-heinen-trio","Bruno Heinen Trio","2026-08-04","U"],
  ["tomorrows-warriors-alex-ho-donovan-haffner","Late Late Show Upstairs with Tomorrow's Warriors: Alex Ho and Donovan Haffner","2026-08-04","X"],
  ["electric-lady-big-band","Denny Ilett’s Electric Lady Big Band plays the music of Jimi Hendrix","2026-08-06","M"],
  ["late-late-show-hosted-by-mark-kavuma","Late Late Show hosted by Mark Kavuma's Banger Factory","2026-12-02","L"],
  ["piano-trio-series-laurie-milton","Piano Trio Series: Laurie Milton","2026-08-06","U"],
  ["shae-universe","Shae Universe","2026-08-07","U"],
  ["kinga-glyk","Kinga Głyk","2026-08-07","M"],
  ["songs-stories-with-jay-rayner","Saturday Brunch: Songs & Stories with Ian Shaw and Jay Rayner","2026-08-08","M"]];
