// Registry of clubs. Each crawler module exports:
//   crawl()      -> fetches live pages and returns events[]
//   parse(input) -> pure function(s) used by crawl(), testable against fixtures
export const CLUBS = [
  {
    id: 'vanguard',
    name: 'Village Vanguard',
    shortName: 'Vanguard',
    url: 'https://villagevanguard.com',
    address: '178 7th Ave S, New York, NY 10014',
    city: 'nyc',
    borough: 'manhattan',
    timezone: 'America/New_York',
    neighborhood: 'West Village',
    color: '#ff453a', // the red neon sign on 7th Ave
    module: './clubs/vanguard.js',
  },
  {
    id: 'bluenote',
    name: 'Blue Note',
    shortName: 'Blue Note',
    url: 'https://www.bluenotejazz.com/nyc',
    address: '131 W 3rd St, New York, NY 10012',
    city: 'nyc',
    borough: 'manhattan',
    timezone: 'America/New_York',
    neighborhood: 'Greenwich Village',
    color: '#4d9bff', // the name — azure, brightened from their navy
    module: './clubs/bluenote.js',
  },
  {
    id: 'smalls',
    name: 'Smalls Jazz Club',
    shortName: 'Smalls',
    url: 'https://www.smallslive.com',
    address: '183 W 10th St, New York, NY 10014',
    city: 'nyc',
    borough: 'manhattan',
    timezone: 'America/New_York',
    neighborhood: 'West Village',
    color: '#e8355f', // SmallsLive brand crimson #d21535, glow-tuned
    module: './clubs/smalls.js',
  },
  {
    id: 'mezzrow',
    name: 'Mezzrow',
    shortName: 'Mezzrow',
    url: 'https://www.smallslive.com',
    address: '163 W 10th St, New York, NY 10014',
    city: 'nyc',
    borough: 'manhattan',
    timezone: 'America/New_York',
    neighborhood: 'West Village',
    color: '#f1bb53', // SmallsLive brand gold, kept as-is
    module: './clubs/smalls.js', // same source feed as Smalls
  },
  {
    id: 'birdland',
    name: 'Birdland',
    shortName: 'Birdland',
    url: 'https://birdlandjazz.com',
    address: '315 W 44th St, New York, NY 10036',
    city: 'nyc',
    borough: 'manhattan',
    timezone: 'America/New_York',
    neighborhood: 'Theater District',
    color: '#f2788c', // birdlandjazz.com brand rose #e7737f
    module: './clubs/birdland.js',
  },
  {
    id: 'jazzgallery',
    name: 'The Jazz Gallery',
    shortName: 'Jazz Gallery',
    url: 'https://jazzgallery.org',
    address: '1158 Broadway, 5th Fl, New York, NY 10001',
    city: 'nyc',
    borough: 'manhattan',
    timezone: 'America/New_York',
    neighborhood: 'NoMad',
    color: '#c96a4a', // their brand dark red #941100 shifted to rust (Vanguard owns red)
    module: './clubs/jazzgallery.js',
  },
  {
    id: 'dizzys',
    name: "Dizzy's Club",
    shortName: "Dizzy's",
    url: 'https://jazz.org/dizzys',
    address: '10 Columbus Cir, New York, NY 10019',
    city: 'nyc',
    borough: 'manhattan',
    timezone: 'America/New_York',
    neighborhood: 'Columbus Circle',
    color: '#ffa042', // the amber room + sunset behind the stage glass
    module: './clubs/dizzys.js',
  },
  {
    id: 'jazzcultural',
    name: 'Jazz Cultural Theater',
    shortName: 'Jazz Cultural',
    url: 'https://www.jazzcultural.com',
    address: '184 W 10th St, New York, NY 10014',
    city: 'nyc',
    borough: 'manhattan',
    timezone: 'America/New_York',
    neighborhood: 'West Village',
    color: '#4a6ff5', // SmallsLive brand royal blue #1055c9, brightened
    module: './clubs/smalls.js', // same SmallsLive feed as Smalls/Mezzrow
  },
  {
    id: 'smoke',
    name: 'Smoke Jazz Club',
    shortName: 'Smoke',
    url: 'https://www.smokejazz.com',
    address: '2751 Broadway, New York, NY 10025',
    city: 'nyc',
    borough: 'manhattan',
    timezone: 'America/New_York',
    neighborhood: 'Upper West Side',
    color: '#9fb6c9', // the name; NB their site brand is red #c51403 if Zach prefers
    module: './clubs/smoke.js',
  },
  {
    id: 'nublu',
    name: 'Nublu 151',
    shortName: 'Nublu',
    url: 'https://nublu.net/program151',
    address: '151 Avenue C, New York, NY 10009',
    city: 'nyc',
    borough: 'manhattan',
    timezone: 'America/New_York',
    neighborhood: 'Alphabet City',
    color: '#35d0e0', // the famous blue light over the unmarked door
    module: './clubs/nublu.js',
  },
  {
    id: 'lunatico',
    name: 'Bar LunÀtico',
    shortName: 'LunÀtico',
    url: 'https://www.barlunatico.com/music',
    address: '486 Halsey St, Brooklyn, NY 11233',
    city: 'nyc',
    borough: 'brooklyn',
    timezone: 'America/New_York',
    neighborhood: 'Bed-Stuy',
    color: '#45c4b5', // barlunatico.com brand teal #4c948b, brightened
    module: './clubs/lunatico.js',
  },
  {
    id: 'django',
    name: 'The Django',
    shortName: 'Django',
    url: 'https://www.thedjangonyc.com',
    address: '2 6th Ave (Roxy Hotel cellar), New York, NY 10013',
    city: 'nyc',
    borough: 'manhattan',
    timezone: 'America/New_York',
    neighborhood: 'Tribeca',
    color: '#8e4ec6', // Parisian-cellar violet — quick read, refine later
    module: './clubs/django.js',
  },
  {
    id: 'cellardog',
    name: 'Cellar Dog',
    shortName: 'Cellar Dog',
    url: 'https://www.cellardog.net',
    address: '75 Christopher St, New York, NY 10014',
    city: 'nyc',
    borough: 'manhattan',
    timezone: 'America/New_York',
    neighborhood: 'West Village',
    color: '#e07b39', // warm basement-lamp orange — quick read
    module: './clubs/cellardog.js',
  },
  {
    id: 'arthurs',
    name: "Arthur's Tavern",
    shortName: "Arthur's",
    url: 'https://www.arthurstavernnyc.com',
    address: '57 Grove St, New York, NY 10014',
    city: 'nyc',
    borough: 'manhattan',
    timezone: 'America/New_York',
    neighborhood: 'West Village',
    color: '#59d95f', // the green neon sign on Grove St
    module: './clubs/arthurs.js',
  },
  {
    id: 'zincbar',
    name: 'Zinc Bar',
    shortName: 'Zinc',
    url: 'https://www.zincbar.com', // NOT zincjazz.com — that domain is hijacked

    address: '82 W 3rd St, New York, NY 10012',
    city: 'nyc',
    borough: 'manhattan',
    timezone: 'America/New_York',
    neighborhood: 'Greenwich Village',
    color: '#aab9cf', // zinc metal — steel-blue grey, quick read
    module: './clubs/zincbar.js',
  },
  {
    id: 'pocket',
    name: 'The Pocket',
    shortName: 'Pocket',
    url: 'https://thepocketnyc.com',
    address: '130 W 46th St, New York, NY 10036',
    city: 'nyc',
    borough: 'manhattan',
    timezone: 'America/New_York',
    neighborhood: 'Theater District',
    color: '#d3e05a', // their chartreuse-on-green brand accent — quick read
    module: './clubs/pocket.js',
  },
  {
    id: 'closeup',
    name: 'Close Up',
    shortName: 'Close Up',
    url: 'https://www.closeupnyc.com',
    address: '154 Orchard St, New York, NY 10002',
    city: 'nyc',
    borough: 'manhattan',
    timezone: 'America/New_York',
    neighborhood: 'Lower East Side',
    color: '#ece5c3', // their cream-on-black calendar palette (FAF9DB), dimmed
    module: './clubs/closeup.js',
  },
  {
    id: 'billsplace',
    name: "Bill's Place",
    shortName: "Bill's Place",
    url: 'https://billsplaceharlem.com',
    address: '148 W 133rd St, New York, NY 10030',
    city: 'nyc',
    borough: 'manhattan',
    timezone: 'America/New_York',
    neighborhood: 'Harlem',
    color: '#a9744f', // speakeasy whiskey brown — quick read
    module: './clubs/billsplace.js',
  },
  {
    id: 'barbes',
    name: 'Barbès',
    shortName: 'Barbès',
    url: 'https://www.barbesbrooklyn.com',
    address: '376 9th St, Brooklyn, NY 11215',
    city: 'nyc',
    borough: 'brooklyn',
    timezone: 'America/New_York',
    neighborhood: 'Park Slope',
    color: '#b04a3d', // their dark-red calendar accent (#850505), glow-tuned
    module: './clubs/barbes.js',
  },
  {
    id: 'ornithology',
    name: 'Ornithology Jazz Club',
    shortName: 'Ornithology',
    url: 'https://ornithologyjazzclub.com',
    address: '6 Suydam St, Brooklyn, NY 11221',
    city: 'nyc',
    borough: 'brooklyn',
    timezone: 'America/New_York',
    neighborhood: 'Bushwick',
    color: '#3fae7f', // Bird — emerald plumage, quick read
    module: './clubs/ornithology.js',
  },
  {
    id: 'ornithologycafe',
    name: 'Ornithology Cafe',
    shortName: 'Orni. Cafe',
    url: 'https://cafeornithology.com',
    address: '1037 Broadway, Brooklyn, NY 11221',
    city: 'nyc',
    borough: 'brooklyn',
    timezone: 'America/New_York',
    neighborhood: 'Bushwick',
    color: '#8fd6a8', // sage — lighter sibling of the club's emerald
    module: './clubs/ornithology.js', // same SpotHopper platform, both rooms
  },
  {
    id: 'barbayeux',
    name: 'Bar Bayeux',
    shortName: 'Bayeux',
    url: 'https://www.barbayeux.com/jazz',
    address: '1066 Nostrand Ave, Brooklyn, NY 11225',
    city: 'nyc',
    borough: 'brooklyn',
    timezone: 'America/New_York',
    neighborhood: 'Prospect-Lefferts',
    color: '#7d9fe0', // tapestry-thread french blue — quick read
    module: './clubs/barbayeux.js',
  },
  {
    id: 'roulette',
    name: 'Roulette Intermedium',
    shortName: 'Roulette',
    url: 'https://roulette.org',
    address: '509 Atlantic Ave, Brooklyn, NY 11217',
    city: 'nyc',
    borough: 'brooklyn',
    timezone: 'America/New_York',
    neighborhood: 'Downtown Brooklyn',
    color: '#9b7bff', // experimental electric violet — quick read
    module: './clubs/roulette.js',
  },
  {
    id: 'jcal',
    name: 'JCAL (Jamaica Center)',
    shortName: 'JCAL',
    url: 'https://jcal.org/events-tickets',
    address: '161-04 Jamaica Ave, Jamaica, NY 11432',
    city: 'nyc',
    borough: 'queens',
    timezone: 'America/New_York',
    neighborhood: 'Jamaica',
    color: '#c2439a', // arts-center magenta — quick read
    module: './clubs/jcal.js',
  },

  // ---------------------------------------------------------------- LA ----
  {
    id: 'samfirst',
    name: 'Sam First',
    shortName: 'Sam First',
    url: 'https://www.samfirstbar.com',
    address: '6171 W Century Blvd 180, Los Angeles, CA 90045',
    city: 'la',
    borough: null,
    timezone: 'America/Los_Angeles',
    neighborhood: 'Westchester / LAX',
    color: '#e0524d', // the red velvet curtain behind the stage — quick read
    module: './clubs/samfirst.js',
  },
  {
    id: 'lacma',
    name: 'Jazz at LACMA',
    shortName: 'LACMA',
    url: 'https://www.lacma.org/programs/music',
    address: '5905 Wilshire Blvd, Los Angeles, CA 90036',
    city: 'la',
    borough: null,
    timezone: 'America/Los_Angeles',
    neighborhood: 'Miracle Mile',
    color: '#f0d98c', // Urban Light lamps at dusk — quick read
    module: './clubs/lacma.js',
  },
  {
    id: 'catalina',
    name: 'Catalina Jazz Club',
    shortName: 'Catalina',
    url: 'https://catalinajazzclub.com',
    address: '6725 W Sunset Blvd, Los Angeles, CA 90028',
    city: 'la',
    borough: null,
    timezone: 'America/Los_Angeles',
    neighborhood: 'Hollywood',
    color: '#5aa0e8', // classic supper-club blue — quick read
    module: './clubs/catalina.js',
  },
  {
    id: 'vibrato',
    name: 'Vibrato Grill Jazz',
    shortName: 'Vibrato',
    url: 'https://www.vibratogrilljazz.com/music',
    address: '2930 Beverly Glen Cir, Los Angeles, CA 90077',
    city: 'la',
    borough: null,
    timezone: 'America/Los_Angeles',
    neighborhood: 'Bel Air',
    color: '#d6a05a', // Herb Alpert's brass — quick read
    module: './clubs/vibrato.js',
  },
  {
    id: 'worldstage',
    name: 'The World Stage',
    shortName: 'World Stage',
    url: 'https://www.theworldstage.org',
    address: '4321 Degnan Blvd, Los Angeles, CA 90008',
    city: 'la',
    borough: null,
    timezone: 'America/Los_Angeles',
    neighborhood: 'Leimert Park',
    color: '#4fc46a', // Leimert Park green — quick read
    module: './clubs/worldstage.js',
  },
  {
    id: 'mint',
    name: 'The Mint',
    shortName: 'Mint',
    url: 'https://themintla.com/events/',
    address: '6010 W Pico Blvd, Los Angeles, CA 90035',
    city: 'la',
    borough: null,
    timezone: 'America/Los_Angeles',
    neighborhood: 'Pico-Robertson',
    color: '#7fd8a4', // mint, naturally — quick read
    module: './clubs/mint.js',
  },
  {
    id: 'hollywoodbowl',
    name: 'Hollywood Bowl',
    shortName: 'Hollywood Bowl',
    url: 'https://www.hollywoodbowl.com',
    address: '2301 N Highland Ave, Los Angeles, CA 90068',
    city: 'la',
    borough: null,
    timezone: 'America/Los_Angeles',
    neighborhood: 'Hollywood Hills',
    color: '#e8e4d8', // the white bandshell arcs — quick read
    module: './clubs/hollywoodbowl.js',
  },
  {
    id: 'twentytwotwenty',
    name: '2220 Arts + Archives',
    shortName: '2220 Arts',
    url: 'https://www.2220arts.org/events',
    address: '2220 Beverly Blvd, Los Angeles, CA 90057',
    city: 'la',
    borough: null,
    timezone: 'America/Los_Angeles',
    neighborhood: 'Historic Filipinotown',
    color: '#d0355c', // their red-on-black poster language — quick read
    module: './clubs/twentytwotwenty.js',
  },
  {
    id: 'zebulon',
    name: 'Zebulon',
    shortName: 'Zebulon',
    url: 'https://zebulon.la',
    address: '2478 Fletcher Dr, Los Angeles, CA 90039',
    city: 'la',
    borough: null,
    timezone: 'America/Los_Angeles',
    neighborhood: 'Frogtown',
    color: '#4ecdc4', // riverbend teal — quick read
    module: './clubs/zebulon.js',
  },
  {
    id: 'harvelles',
    name: "Harvelle's",
    shortName: "Harvelle's",
    url: 'https://santamonica.harvelles.com',
    address: '1432 4th St, Santa Monica, CA 90401',
    city: 'la',
    borough: null,
    timezone: 'America/Los_Angeles',
    neighborhood: 'Santa Monica',
    color: '#8c3a5f', // red-velvet wine, 1931 speakeasy — quick read
    module: './clubs/harvelles.js',
  },
];

export function clubById(id) {
  return CLUBS.find((c) => c.id === id);
}
