// Registry of clubs. Each crawler module exports:
//   crawl()      -> fetches live pages and returns events[]
//   parse(input) -> pure function(s) used by crawl(), testable against fixtures
export const CLUBS = [
  {
    id: 'vanguard',
    name: 'Village Vanguard',
    shortName: 'Vanguard',
    url: 'https://villagevanguard.com',
    address: '178 7th Ave S, New York, NY 10014',
    city: 'nyc',
    borough: 'manhattan',
    timezone: 'America/New_York',
    neighborhood: 'West Village',
    color: '#ff453a', // the red neon sign on 7th Ave
    module: './clubs/vanguard.js',
  },
  {
    id: 'bluenote',
    name: 'Blue Note',
    shortName: 'Blue Note',
    url: 'https://www.bluenotejazz.com/nyc',
    address: '131 W 3rd St, New York, NY 10012',
    city: 'nyc',
    borough: 'manhattan',
    timezone: 'America/New_York',
    neighborhood: 'Greenwich Village',
    color: '#4d9bff', // the name — azure, brightened from their navy
    module: './clubs/bluenote.js',
  },
  {
    id: 'smalls',
    name: 'Smalls Jazz Club',
    shortName: 'Smalls',
    url: 'https://www.smallslive.com',
    address: '183 W 10th St, New York, NY 10014',
    city: 'nyc',
    borough: 'manhattan',
    timezone: 'America/New_York',
    neighborhood: 'West Village',
    color: '#e8355f', // SmallsLive brand crimson #d21535, glow-tuned
    module: './clubs/smalls.js',
  },
  {
    id: 'mezzrow',
    name: 'Mezzrow',
    shortName: 'Mezzrow',
    url: 'https://www.smallslive.com',
    address: '163 W 10th St, New York, NY 10014',
    city: 'nyc',
    borough: 'manhattan',
    timezone: 'America/New_York',
    neighborhood: 'West Village',
    color: '#f1bb53', // SmallsLive brand gold, kept as-is
    module: './clubs/smalls.js', // same source feed as Smalls
  },
  {
    id: 'birdland',
    name: 'Birdland',
    shortName: 'Birdland',
    url: 'https://birdlandjazz.com',
    address: '315 W 44th St, New York, NY 10036',
    city: 'nyc',
    borough: 'manhattan',
    timezone: 'America/New_York',
    neighborhood: 'Theater District',
    color: '#f2788c', // birdlandjazz.com brand rose #e7737f
    module: './clubs/birdland.js',
  },
  {
    id: 'jazzgallery',
    name: 'The Jazz Gallery',
    shortName: 'Jazz Gallery',
    url: 'https://jazzgallery.org',
    address: '1158 Broadway, 5th Fl, New York, NY 10001',
    city: 'nyc',
    borough: 'manhattan',
    timezone: 'America/New_York',
    neighborhood: 'NoMad',
    color: '#c96a4a', // their brand dark red #941100 shifted to rust (Vanguard owns red)
    module: './clubs/jazzgallery.js',
  },
  {
    id: 'dizzys',
    name: "Dizzy's Club",
    shortName: "Dizzy's",
    url: 'https://jazz.org/dizzys',
    address: '10 Columbus Cir, New York, NY 10019',
    city: 'nyc',
    borough: 'manhattan',
    timezone: 'America/New_York',
    neighborhood: 'Columbus Circle',
    color: '#ff8929', // the amber room + sunset, deepened clear of Mezzrow's gold
    module: './clubs/dizzys.js',
  },
  {
    id: 'jazzcultural',
    name: 'Jazz Cultural Theater',
    shortName: 'Jazz Cultural',
    url: 'https://www.jazzcultural.com',
    address: '184 W 10th St, New York, NY 10014',
    city: 'nyc',
    borough: 'manhattan',
    timezone: 'America/New_York',
    neighborhood: 'West Village',
    color: '#3d55e0', // SmallsLive brand royal blue #1055c9 — indigo, clear of Blue Note
    module: './clubs/smalls.js', // same SmallsLive feed as Smalls/Mezzrow
  },
  {
    id: 'smoke',
    name: 'Smoke Jazz Club',
    shortName: 'Smoke',
    url: 'https://www.smokejazz.com',
    address: '2751 Broadway, New York, NY 10025',
    city: 'nyc',
    borough: 'manhattan',
    timezone: 'America/New_York',
    neighborhood: 'Upper West Side',
    color: '#b83226', // their brand red #c51403 deepened to brick (Vanguard keeps bright red)
    module: './clubs/smoke.js',
  },
  {
    id: 'nublu',
    name: 'Nublu 151',
    shortName: 'Nublu',
    url: 'https://nublu.net/program151',
    address: '151 Avenue C, New York, NY 10009',
    city: 'nyc',
    borough: 'manhattan',
    timezone: 'America/New_York',
    neighborhood: 'Alphabet City',
    color: '#35d0e0', // the famous blue light over the unmarked door
    module: './clubs/nublu.js',
  },
  {
    id: 'lunatico',
    name: 'Bar LunÀtico',
    shortName: 'LunÀtico',
    url: 'https://www.barlunatico.com/music',
    address: '486 Halsey St, Brooklyn, NY 11233',
    city: 'nyc',
    borough: 'brooklyn',
    timezone: 'America/New_York',
    neighborhood: 'Bed-Stuy',
    color: '#2fa88c', // barlunatico.com brand teal, deepened sea-green clear of Nublu
    module: './clubs/lunatico.js',
  },
  {
    id: 'django',
    name: 'The Django',
    shortName: 'Django',
    url: 'https://www.thedjangonyc.com',
    address: '2 6th Ave (Roxy Hotel cellar), New York, NY 10013',
    city: 'nyc',
    borough: 'manhattan',
    timezone: 'America/New_York',
    neighborhood: 'Tribeca',
    color: '#8e4ec6', // Parisian-cellar violet — quick read, refine later
    module: './clubs/django.js',
  },
  {
    id: 'cellardog',
    name: 'Cellar Dog',
    shortName: 'Cellar Dog',
    url: 'https://www.cellardog.net',
    address: '75 Christopher St, New York, NY 10014',
    city: 'nyc',
    borough: 'manhattan',
    timezone: 'America/New_York',
    neighborhood: 'West Village',
    color: '#e07b39', // warm basement-lamp orange — quick read
    module: './clubs/cellardog.js',
  },
  {
    id: 'arthurs',
    name: "Arthur's Tavern",
    shortName: "Arthur's",
    url: 'https://www.arthurstavernnyc.com',
    address: '57 Grove St, New York, NY 10014',
    city: 'nyc',
    borough: 'manhattan',
    timezone: 'America/New_York',
    neighborhood: 'West Village',
    color: '#59d95f', // the green neon sign on Grove St
    module: './clubs/arthurs.js',
  },
  {
    id: 'zincbar',
    name: 'Zinc Bar',
    shortName: 'Zinc',
    url: 'https://www.zincbar.com', // NOT zincjazz.com — that domain is hijacked

    address: '82 W 3rd St, New York, NY 10012',
    city: 'nyc',
    borough: 'manhattan',
    timezone: 'America/New_York',
    neighborhood: 'Greenwich Village',
    color: '#aab9cf', // zinc metal — steel-blue grey, quick read
    module: './clubs/zincbar.js',
  },
  {
    id: 'pocket',
    name: 'The Pocket',
    shortName: 'Pocket',
    url: 'https://thepocketnyc.com',
    address: '130 W 46th St, New York, NY 10036',
    city: 'nyc',
    borough: 'manhattan',
    timezone: 'America/New_York',
    neighborhood: 'Theater District',
    color: '#d3e05a', // their chartreuse-on-green brand accent — quick read
    module: './clubs/pocket.js',
  },
  {
    id: 'closeup',
    name: 'Close Up',
    shortName: 'Close Up',
    url: 'https://www.closeupnyc.com',
    address: '154 Orchard St, New York, NY 10002',
    city: 'nyc',
    borough: 'manhattan',
    timezone: 'America/New_York',
    neighborhood: 'Lower East Side',
    color: '#ece5c3', // their cream-on-black calendar palette (FAF9DB), dimmed
    module: './clubs/closeup.js',
  },
  {
    id: 'billsplace',
    name: "Bill's Place",
    shortName: "Bill's Place",
    url: 'https://billsplaceharlem.com',
    address: '148 W 133rd St, New York, NY 10030',
    city: 'nyc',
    borough: 'harlem',
    timezone: 'America/New_York',
    neighborhood: 'Harlem',
    color: '#8a5a3a', // speakeasy walnut — darker, clear of Jazz Gallery's rust
    module: './clubs/billsplace.js',
  },
  {
    id: 'barbes',
    name: 'Barbès',
    shortName: 'Barbès',
    url: 'https://www.barbesbrooklyn.com',
    address: '376 9th St, Brooklyn, NY 11215',
    city: 'nyc',
    borough: 'brooklyn',
    timezone: 'America/New_York',
    neighborhood: 'Park Slope',
    color: '#93323c', // their dark-red calendar accent (#850505) — deep claret
    module: './clubs/barbes.js',
  },
  {
    id: 'ornithology',
    name: 'Ornithology Jazz Club',
    shortName: 'Ornithology',
    url: 'https://ornithologyjazzclub.com',
    address: '6 Suydam St, Brooklyn, NY 11221',
    city: 'nyc',
    borough: 'brooklyn',
    timezone: 'America/New_York',
    neighborhood: 'Bushwick',
    color: '#3fae7f', // Bird — emerald plumage, quick read
    module: './clubs/ornithology.js',
  },
  {
    id: 'ornithologycafe',
    name: 'Ornithology Cafe',
    shortName: 'Orni. Cafe',
    url: 'https://cafeornithology.com',
    address: '1037 Broadway, Brooklyn, NY 11221',
    city: 'nyc',
    borough: 'brooklyn',
    timezone: 'America/New_York',
    neighborhood: 'Bushwick',
    color: '#8fd6a8', // sage — lighter sibling of the club's emerald
    module: './clubs/ornithology.js', // same SpotHopper platform, both rooms
  },
  {
    id: 'barbayeux',
    name: 'Bar Bayeux',
    shortName: 'Bayeux',
    url: 'https://www.barbayeux.com/jazz',
    address: '1066 Nostrand Ave, Brooklyn, NY 11225',
    city: 'nyc',
    borough: 'brooklyn',
    timezone: 'America/New_York',
    neighborhood: 'Prospect-Lefferts',
    color: '#7d9fe0', // tapestry-thread french blue — quick read
    module: './clubs/barbayeux.js',
  },
  {
    id: 'roulette',
    name: 'Roulette Intermedium',
    shortName: 'Roulette',
    url: 'https://roulette.org',
    address: '509 Atlantic Ave, Brooklyn, NY 11217',
    city: 'nyc',
    borough: 'brooklyn',
    timezone: 'America/New_York',
    neighborhood: 'Downtown Brooklyn',
    color: '#9b7bff', // experimental electric violet — quick read
    module: './clubs/roulette.js',
  },
  {
    id: 'jcal',
    name: 'JCAL (Jamaica Center)',
    shortName: 'JCAL',
    url: 'https://jcal.org/events-tickets',
    address: '161-04 Jamaica Ave, Jamaica, NY 11432',
    city: 'nyc',
    borough: 'queens',
    timezone: 'America/New_York',
    neighborhood: 'Jamaica',
    color: '#c2439a', // arts-center magenta — quick read
    module: './clubs/jcal.js',
  },
  {
    id: 'silvana',
    name: 'Silvana',
    shortName: 'Silvana',
    url: 'https://silvana-nyc.com/calendar.php',
    address: '300 W 116th St, New York, NY 10026',
    city: 'nyc',
    borough: 'harlem',
    timezone: 'America/New_York',
    neighborhood: 'Harlem',
    color: '#ff6ec7', // the basement stage lights — hot pink, audit-cleared
    module: './clubs/silvana.js',
  },
  {
    id: 'shrine',
    name: 'Shrine World Music Venue',
    shortName: 'Shrine',
    url: 'https://shrinenyc.com/calendar.php',
    address: '2271 Adam Clayton Powell Jr Blvd, New York, NY 10030',
    city: 'nyc',
    borough: 'harlem',
    timezone: 'America/New_York',
    neighborhood: 'Harlem',
    color: '#265c8c', // world-stage deep blue — audit-cleared
    module: './clubs/silvana.js', // same homegrown calendar as sister venue Silvana
  },
  {
    id: 'sistasplace',
    name: "Sistas' Place",
    shortName: "Sistas' Place",
    url: 'https://sistasplace.org',
    address: '456 Nostrand Ave, Brooklyn, NY 11216',
    city: 'nyc',
    borough: 'brooklyn',
    timezone: 'America/New_York',
    neighborhood: 'Bed-Stuy',
    color: '#2e8c5a', // liberation green — true to the movement institution
    module: './clubs/sistasplace.js',
  },
  {
    id: 'terraza7',
    name: 'Terraza 7',
    shortName: 'Terraza 7',
    url: 'https://www.terraza7.com/events',
    address: '40-19 Gleane St, Elmhurst, NY 11373',
    city: 'nyc',
    borough: 'queens',
    timezone: 'America/New_York',
    neighborhood: 'Elmhurst',
    color: '#7ce8d5', // Andean turquoise — audit-cleared
    module: './clubs/terraza7.js',
  },
  {
    id: 'marjorie',
    name: "Marjorie Eliot's Parlor Jazz",
    shortName: "Marjorie's",
    url: 'https://www.facebook.com/pages/Marjorie-Elliots-Parlor-Jazz/488061981215540',
    address: '555 Edgecombe Ave Apt 3F, New York, NY 10032',
    city: 'nyc',
    borough: 'harlem',
    timezone: 'America/New_York',
    neighborhood: 'Sugar Hill',
    color: '#e8a0b8', // Sunday-dress parlor rose — audit-cleared
    module: './clubs/marjorie.js',
  },

  // ---------------------------------------------------------------- LA ----
  {
    id: 'samfirst',
    name: 'Sam First',
    shortName: 'Sam First',
    url: 'https://www.samfirstbar.com',
    address: '6171 W Century Blvd 180, Los Angeles, CA 90045',
    city: 'la',
    borough: null,
    timezone: 'America/Los_Angeles',
    neighborhood: 'Westchester / LAX',
    color: '#e0524d', // the red velvet curtain behind the stage — quick read
    module: './clubs/samfirst.js',
  },
  {
    id: 'lacma',
    name: 'Jazz at LACMA',
    shortName: 'LACMA',
    url: 'https://www.lacma.org/programs/music',
    address: '5905 Wilshire Blvd, Los Angeles, CA 90036',
    city: 'la',
    borough: null,
    timezone: 'America/Los_Angeles',
    neighborhood: 'Miracle Mile',
    color: '#f0d98c', // Urban Light lamps at dusk — quick read
    module: './clubs/lacma.js',
  },
  {
    id: 'catalina',
    name: 'Catalina Jazz Club',
    shortName: 'Catalina',
    url: 'https://catalinajazzclub.com',
    address: '6725 W Sunset Blvd, Los Angeles, CA 90028',
    city: 'la',
    borough: null,
    timezone: 'America/Los_Angeles',
    neighborhood: 'Hollywood',
    color: '#5aa0e8', // classic supper-club blue — quick read
    module: './clubs/catalina.js',
  },
  {
    id: 'vibrato',
    name: 'Vibrato Grill Jazz',
    shortName: 'Vibrato',
    url: 'https://www.vibratogrilljazz.com/music',
    address: '2930 Beverly Glen Cir, Los Angeles, CA 90077',
    city: 'la',
    borough: null,
    timezone: 'America/Los_Angeles',
    neighborhood: 'Bel Air',
    color: '#d6a05a', // Herb Alpert's brass — quick read
    module: './clubs/vibrato.js',
  },
  {
    id: 'worldstage',
    name: 'The World Stage',
    shortName: 'World Stage',
    url: 'https://www.theworldstage.org',
    address: '4321 Degnan Blvd, Los Angeles, CA 90008',
    city: 'la',
    borough: null,
    timezone: 'America/Los_Angeles',
    neighborhood: 'Leimert Park',
    color: '#4fc46a', // Leimert Park green — quick read
    module: './clubs/worldstage.js',
  },
  {
    id: 'mint',
    name: 'The Mint',
    shortName: 'Mint',
    url: 'https://themintla.com/events/',
    address: '6010 W Pico Blvd, Los Angeles, CA 90035',
    city: 'la',
    borough: null,
    timezone: 'America/Los_Angeles',
    neighborhood: 'Pico-Robertson',
    color: '#7fd8a4', // mint, naturally — quick read
    module: './clubs/mint.js',
  },
  {
    id: 'hollywoodbowl',
    name: 'Hollywood Bowl',
    shortName: 'Hollywood Bowl',
    url: 'https://www.hollywoodbowl.com',
    address: '2301 N Highland Ave, Los Angeles, CA 90068',
    city: 'la',
    borough: null,
    timezone: 'America/Los_Angeles',
    neighborhood: 'Hollywood Hills',
    color: '#e8e4d8', // the white bandshell arcs — quick read
    module: './clubs/laphil.js', // one LA Phil feed serves Bowl + Disney Hall + Ford
  },
  {
    id: 'disneyhall',
    name: 'Walt Disney Concert Hall',
    shortName: 'Disney Hall',
    url: 'https://www.laphil.com',
    address: '111 S Grand Ave, Los Angeles, CA 90012',
    city: 'la',
    borough: null,
    timezone: 'America/Los_Angeles',
    neighborhood: 'Downtown',
    color: '#b8c4d4', // Gehry's stainless-steel curves — audit-cleared
    module: './clubs/laphil.js',
  },
  {
    id: 'theford',
    name: 'The Ford',
    shortName: 'The Ford',
    url: 'https://www.theford.com',
    address: '2580 Cahuenga Blvd E, Los Angeles, CA 90068',
    city: 'la',
    borough: null,
    timezone: 'America/Los_Angeles',
    neighborhood: 'Cahuenga Pass',
    color: '#a0522d', // canyon-rock sienna — audit-cleared
    module: './clubs/laphil.js',
  },
  {
    id: 'golddiggers',
    name: 'Gold-Diggers',
    shortName: 'Gold-Diggers',
    url: 'https://gold-diggers.com/pages/drink',
    address: '5632 Santa Monica Blvd, Los Angeles, CA 90038',
    city: 'la',
    borough: null,
    timezone: 'America/Los_Angeles',
    neighborhood: 'East Hollywood',
    color: '#b8901f', // antique gold, naturally — audit-cleared
    module: './clubs/golddiggers.js',
  },
  {
    id: 'twentytwotwenty',
    name: '2220 Arts + Archives',
    shortName: '2220 Arts',
    url: 'https://www.2220arts.org/events',
    address: '2220 Beverly Blvd, Los Angeles, CA 90057',
    city: 'la',
    borough: null,
    timezone: 'America/Los_Angeles',
    neighborhood: 'Historic Filipinotown',
    color: '#d62a72', // their red-on-black poster language, pushed magenta clear of Sam First
    module: './clubs/twentytwotwenty.js',
  },
  {
    id: 'zebulon',
    name: 'Zebulon',
    shortName: 'Zebulon',
    url: 'https://zebulon.la',
    address: '2478 Fletcher Dr, Los Angeles, CA 90039',
    city: 'la',
    borough: null,
    timezone: 'America/Los_Angeles',
    neighborhood: 'Frogtown',
    color: '#4ecdc4', // riverbend teal — quick read
    module: './clubs/zebulon.js',
  },
  {
    id: 'harvelles',
    name: "Harvelle's",
    shortName: "Harvelle's",
    url: 'https://santamonica.harvelles.com',
    address: '1432 4th St, Santa Monica, CA 90401',
    city: 'la',
    borough: null,
    timezone: 'America/Los_Angeles',
    neighborhood: 'Santa Monica',
    color: '#b34d7a', // red-velvet wine, brightened to read on black
    module: './clubs/harvelles.js',
  },

  // ----------------------------------------------------------- Chicago ----
  {
    id: 'greenmill',
    name: 'Green Mill',
    shortName: 'Green Mill',
    url: 'https://greenmilljazz.com',
    address: '4802 N Broadway, Chicago, IL 60640',
    city: 'chi',
    borough: null,
    timezone: 'America/Chicago',
    neighborhood: 'Uptown',
    color: '#3ddc74', // the green neon over Broadway — the sign IS the club
    module: './clubs/greenmill.js',
  },
  {
    id: 'jazzshowcase',
    name: 'Jazz Showcase',
    shortName: 'Showcase',
    url: 'https://www.jazzshowcase.com',
    address: '806 S Plymouth Ct, Chicago, IL 60605',
    city: 'chi',
    borough: null,
    timezone: 'America/Chicago',
    neighborhood: 'South Loop',
    color: '#d94343', // Segal's red curtain + Bird watching from every poster
    module: './clubs/jazzshowcase.js',
  },
  {
    id: 'andys',
    name: "Andy's Jazz Club",
    shortName: "Andy's",
    url: 'https://andysjazzclub.com',
    address: '11 E Hubbard St, Chicago, IL 60611',
    city: 'chi',
    borough: null,
    timezone: 'America/Chicago',
    neighborhood: 'River North',
    color: '#e8a13d', // brass-and-barlight amber — audit-cleared
    module: './clubs/andys.js',
  },
  {
    id: 'winters',
    name: "Winter's Jazz Club",
    shortName: "Winter's",
    url: 'https://www.wintersjazzclub.com',
    address: '465 N McClurg Ct, Chicago, IL 60611',
    city: 'chi',
    borough: null,
    timezone: 'America/Chicago',
    neighborhood: 'Streeterville',
    color: '#9fd4ef', // winter ice off the lakefront — audit-cleared
    module: './clubs/winters.js',
  },
  {
    id: 'constellation',
    name: 'Constellation',
    shortName: 'Constellation',
    url: 'https://constellation-chicago.com',
    address: '3111 N Western Ave, Chicago, IL 60618',
    city: 'chi',
    borough: null,
    timezone: 'America/Chicago',
    neighborhood: 'Roscoe Village',
    color: '#6b7fff', // star-chart indigo — audit-cleared
    module: './clubs/constellation.js',
  },
  {
    id: 'hungrybrain',
    name: 'Hungry Brain',
    shortName: 'Hungry Brain',
    url: 'https://hungrybrainchicago.com',
    address: '2319 W Belmont Ave, Chicago, IL 60618',
    city: 'chi',
    borough: null,
    timezone: 'America/Chicago',
    neighborhood: 'Roscoe Village',
    color: '#ff7f9e', // the pink neon brain behind the bar — audit-cleared
    module: './clubs/hungrybrain.js',
  },
  {
    id: 'elasticarts',
    name: 'Elastic Arts',
    shortName: 'Elastic',
    url: 'https://elasticarts.org',
    address: '3429 W Diversey Ave #208, Chicago, IL 60647',
    city: 'chi',
    borough: null,
    timezone: 'America/Chicago',
    neighborhood: 'Logan Square',
    color: '#a06be8', // loft-scene violet — audit-cleared
    module: './clubs/elasticarts.js',
  },
  {
    id: 'space',
    name: 'SPACE',
    shortName: 'SPACE',
    url: 'https://evanstonspace.com',
    address: '1245 Chicago Ave, Evanston, IL 60202',
    city: 'chi',
    borough: null,
    timezone: 'America/Chicago',
    neighborhood: 'Evanston',
    color: '#efe3bb', // marquee-bulb cream — audit-cleared
    module: './clubs/space.js',
  },
  {
    id: 'dorians',
    name: "Dorian's",
    shortName: "Dorian's",
    url: 'https://throughtherecordshop.com',
    address: '1939 W North Ave, Chicago, IL 60622',
    city: 'chi',
    borough: null,
    timezone: 'America/Chicago',
    neighborhood: 'Wicker Park',
    color: '#3fb8af', // cocktail-glass teal behind the record bins — audit-cleared
    module: './clubs/dorians.js',
  },

  // ----------------------------------------------------- San Francisco ----
  {
    id: 'sfjazz',
    name: 'SFJAZZ',
    shortName: 'SFJAZZ',
    url: 'https://www.sfjazz.org',
    address: '201 Franklin St, San Francisco, CA 94102',
    city: 'sf',
    borough: null,
    timezone: 'America/Los_Angeles',
    neighborhood: 'Hayes Valley',
    color: '#ff6a3d', // their poster orange, glow-tuned for black
    module: './clubs/sfjazz.js',
  },
  {
    id: 'blackcat',
    name: 'Black Cat',
    shortName: 'Black Cat',
    url: 'https://blackcatsf.com',
    address: '400 Eddy St, San Francisco, CA 94109',
    city: 'sf',
    borough: null,
    timezone: 'America/Los_Angeles',
    neighborhood: 'Tenderloin',
    color: '#f1c04f', // cat-eye gold on black, their own palette
    module: './clubs/blackcat.js',
  },
  {
    id: 'keys',
    name: 'Keys Jazz Bistro',
    shortName: 'Keys',
    url: 'https://keysjazzbistro.com',
    address: '498 Broadway, San Francisco, CA 94133',
    city: 'sf',
    borough: null,
    timezone: 'America/Los_Angeles',
    neighborhood: 'North Beach',
    color: '#c92f4c', // Broadway-corridor neon crimson — audit-cleared
    module: './clubs/keys.js',
  },
  {
    id: 'mrtipples',
    name: "Mr. Tipple's",
    shortName: "Tipple's",
    url: 'https://mrtipplessf.com',
    address: '39 Fell St, San Francisco, CA 94102',
    city: 'sf',
    borough: null,
    timezone: 'America/Los_Angeles',
    neighborhood: 'Civic Center',
    color: '#9b59d0', // low-lit cocktail-den violet — audit-cleared
    module: './clubs/mrtipples.js',
  },
  {
    id: 'birdbeckett',
    name: 'Bird & Beckett',
    shortName: 'Bird & Beckett',
    url: 'https://birdbeckett.com',
    address: '653 Chenery St, San Francisco, CA 94131',
    city: 'sf',
    borough: null,
    timezone: 'America/Los_Angeles',
    neighborhood: 'Glen Park',
    color: '#8fbf6f', // bookshop-shelf sage — audit-cleared
    module: './clubs/birdbeckett.js',
  },
  {
    id: 'freight',
    name: 'Freight & Salvage',
    shortName: 'Freight',
    url: 'https://thefreight.org',
    address: '2020 Addison St, Berkeley, CA 94704',
    city: 'sf',
    borough: null,
    timezone: 'America/Los_Angeles',
    neighborhood: 'Downtown Berkeley',
    color: '#45c4bc', // workshop-patina teal — audit-cleared
    module: './clubs/freight.js',
  },
  {
    id: 'yoshis',
    name: "Yoshi's",
    shortName: "Yoshi's",
    url: 'https://yoshis.com',
    address: '510 Embarcadero W, Oakland, CA 94607',
    city: 'sf',
    borough: null,
    timezone: 'America/Los_Angeles',
    neighborhood: 'Jack London Square, Oakland',
    color: '#4a90d9', // harbor-water blue — audit-cleared
    module: './clubs/yoshis.js',
  },
];

export function clubById(id) {
  return CLUBS.find((c) => c.id === id);
}
