// Offline bundler: builds web/dist without npm/Vite, using the globally
// installed typescript + react packages. Used in environments where the npm
// registry is unreachable. Normal development uses Vite (`npm run dev/build`).
//
//   node build-offline.mjs
//
// Steps: tsc-transpile src/*.jsx -> CJS, then wrap app modules + react's CJS
// files in a tiny CommonJS loader and emit dist/bundle.js + dist/index.html.
import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync, rmSync, readdirSync, statSync, copyFileSync, existsSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC = join(__dirname, 'src');
const TMP = join(__dirname, '.tmp-offline');
const DIST = join(__dirname, 'dist');

// Locate global node_modules (where react/react-dom/typescript live).
const GLOBALS = [
  '/home/claude/.npm-global/lib/node_modules',
  execSync('npm root -g', { encoding: 'utf8' }).trim(),
].filter((p) => existsSync(join(p, 'react')));
const G = GLOBALS[0];
if (!G) throw new Error('global react not found; use Vite instead (npm run build)');

// 1. transpile ------------------------------------------------------------
rmSync(TMP, { recursive: true, force: true });
const srcFiles = [];
(function walk(dir) {
  for (const f of readdirSync(dir)) {
    const p = join(dir, f);
    if (statSync(p).isDirectory()) walk(p);
    else if (/\.(jsx|js)$/.test(f)) srcFiles.push(p);
  }
})(SRC);
execSync(
  `tsc ${srcFiles.map((f) => `"${f}"`).join(' ')} --jsx react-jsx --module commonjs ` +
  `--target es2020 --esModuleInterop --allowJs --noCheck --outDir "${TMP}"`,
  { stdio: 'inherit' }
);

// 2. collect modules --------------------------------------------------------
const modules = new Map(); // id -> source

function addFile(id, path) {
  modules.set(id, readFileSync(path, 'utf8'));
}
// app modules (compiled): ids like "app/main.js", "app/components/FilterBar.js"
(function walk(dir, prefix) {
  for (const f of readdirSync(dir)) {
    const p = join(dir, f);
    if (statSync(p).isDirectory()) walk(p, `${prefix}${f}/`);
    else if (f.endsWith('.js')) addFile(`app/${prefix}${f}`, p);
  }
})(TMP, '');

// react + friends (production CJS)
const LIB = {
  'node_modules/react/index.js': join(G, 'react/index.js'),
  'node_modules/react/jsx-runtime.js': join(G, 'react/jsx-runtime.js'),
  'node_modules/react/cjs/react.production.js': join(G, 'react/cjs/react.production.js'),
  'node_modules/react/cjs/react-jsx-runtime.production.js': join(G, 'react/cjs/react-jsx-runtime.production.js'),
  'node_modules/react-dom/index.js': join(G, 'react-dom/index.js'),
  'node_modules/react-dom/client.js': join(G, 'react-dom/client.js'),
  'node_modules/react-dom/cjs/react-dom.production.js': join(G, 'react-dom/cjs/react-dom.production.js'),
  'node_modules/react-dom/cjs/react-dom-client.production.js': join(G, 'react-dom/cjs/react-dom-client.production.js'),
  'node_modules/scheduler/index.js': join(G, 'react-dom/node_modules/scheduler/index.js'),
  'node_modules/scheduler/cjs/scheduler.production.js': join(G, 'react-dom/node_modules/scheduler/cjs/scheduler.production.js'),
};
for (const [id, p] of Object.entries(LIB)) addFile(id, p);

// 3. emit bundle -------------------------------------------------------------
const BARE = {
  react: 'node_modules/react/index.js',
  'react/jsx-runtime': 'node_modules/react/jsx-runtime.js',
  'react-dom': 'node_modules/react-dom/index.js',
  'react-dom/client': 'node_modules/react-dom/client.js',
  scheduler: 'node_modules/scheduler/index.js',
};

let out = `// generated by build-offline.mjs — do not edit
(function () {
'use strict';
var process = { env: { NODE_ENV: 'production' } };
var __defs = {}, __cache = {};
function __norm(parts) {
  var st = [];
  for (var i = 0; i < parts.length; i++) {
    var p = parts[i];
    if (p === '' || p === '.') continue;
    if (p === '..') st.pop(); else st.push(p);
  }
  return st.join('/');
}
var __bare = ${JSON.stringify(BARE)};
function __resolve(from, spec) {
  if (spec.endsWith('.css')) return null;
  if (spec[0] !== '.') {
    if (__bare[spec]) return __bare[spec];
    throw new Error('unresolved: ' + spec);
  }
  var base = from.split('/').slice(0, -1);
  var id = __norm(base.concat(spec.split('/')));
  if (__defs[id]) return id;
  if (__defs[id + '.js']) return id + '.js';
  throw new Error('unresolved: ' + spec + ' from ' + from);
}
function __require(from, spec) {
  var id = __resolve(from, spec);
  if (id === null) return {};
  if (__cache[id]) return __cache[id].exports;
  var mod = { exports: {} };
  __cache[id] = mod;
  __defs[id].call(mod.exports, mod, mod.exports, function (s) { return __require(id, s); });
  return mod.exports;
}
`;
for (const [id, src] of modules) {
  out += `__defs[${JSON.stringify(id)}] = function (module, exports, require) {\n${src}\n};\n`;
}
out += `__require('app/', './main.js');\n})();\n`;

rmSync(DIST, { recursive: true, force: true });
mkdirSync(DIST, { recursive: true });
writeFileSync(join(DIST, 'bundle.js'), out);
copyFileSync(join(SRC, 'styles.css'), join(DIST, 'styles.css'));
writeFileSync(join(DIST, 'index.html'), `<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>JazzMap NYC — live jazz tonight</title>
<link rel="stylesheet" href="/styles.css" />
</head>
<body>
<div id="root"></div>
<script src="/bundle.js"></script>
</body>
</html>
`);
rmSync(TMP, { recursive: true, force: true });
console.log(`built dist/bundle.js (${Math.round(out.length / 1024)} KB) + index.html`);
